
module.exports = loadWebAssembly

loadWebAssembly.supported = typeof WebAssembly !== 'undefined'

function loadWebAssembly (opts) {
  if (!loadWebAssembly.supported) return null

  var imp = opts && opts.imports
  var wasm = toUint8Array('AGFzbQEAAAABGgVgA39/fwBgAX8AYAABf2ABfwF/YAJ/fwF/AiMCA2Vudg11dWlkX2dlbmVyYXRlAAEDZW52Bm1lbW9yeQIAAgMGBQADAgQABicGfwFB0IgEC38AQYAIC38AQYQIC38AQYgIC38AQYwIC38AQdCIBAsHwgEJDWh5cGVyaWRfY291bnQAAh5oeXBlcmlkX3Jlc3VsdF9lbmNvZGluZ19sZW5ndGgAAxBoeXBlcmlkX2dlbmVyYXRlAAQMaHlwZXJpZF9tYWtlAAUTc2l6ZW9mX2h5cGVyaWRfVVVJRAMBFnNpemVvZl9oeXBlcmlkX09wdGlvbnMDAhZzaXplb2ZfaHlwZXJpZF9Db250ZXh0AwMVc2l6ZW9mX2h5cGVyaWRfUmVzdWx0AwQLX19oZWFwX2Jhc2UDBQrZDAX6AgICfwF+AkAgAkUNACAAIAE6AAAgACACaiIDQX9qIAE6AAAgAkEDSQ0AIAAgAToAAiAAIAE6AAEgA0F9aiABOgAAIANBfmogAToAACACQQdJDQAgACABOgADIANBfGogAToAACACQQlJDQBBACAAa0EDcSIEIABqIgMgAUH/AXFBgYKECGwiADYCACACIARrQXxxIgIgA2oiAUF8aiAANgIAIAJBCUkNACADIAA2AgggAyAANgIEIAFBeGogADYCACABQXRqIAA2AgAgAkEZSQ0AIAMgADYCGCADIAA2AhQgAyAANgIQIAMgADYCDCABQXBqIAA2AgAgAUFsaiAANgIAIAFBaGogADYCACABQWRqIAA2AgAgAiADQQRxQRhyIgFrIgJBIEkNACAArSIFIAVCIIaEIQUgASADaiEBA0AgASAFNwMAIAFBGGogBTcDACABQRBqIAU3AwAgAUEIaiAFNwMAIAFBIGohASACQWBqIgJBH0sNAAsLCwcAIAAoAhQLBABBIguHBAEDfwJ/QQogACgCFCICQf+T69wDSw0AGkEJIAJB/8HXL0sNABpBCCACQf+s4gRLDQAaQQcgAkG/hD1LDQAaQQYgAkGfjQZLDQAaQQUgAkGPzgBLDQAaQQQgAkHnB0sNABpBAyACQeMASw0AGkECQQEgAkEJSxsLIQMgASAALQAYOgAAIAEgAEEZai0AADoAASABIABBGmotAAA6AAIgASAAQRtqLQAAOgADIAEgAEEcai0AADoABCABIABBHWotAAA6AAUgASAAQR5qLQAAOgAGIAEgAEEfai0AADoAByABIABBIGotAAA6AAggASAAQSFqLQAAOgAJIAEgAEEiai0AADoACiABIABBI2otAAA6AAsgASAAQSRqLQAAOgAMIAEgAEElai0AADoADSABIABBJmotAAA6AA4gASAAQSdqLQAAOgAPIAEgAEEoai0AADoAECABIABBKWotAAA6ABEgASAAQSpqLQAAOgASIAEgAEErai0AADoAEyABIABBLGotAAA6ABQgASAAQS1qLQAAOgAVIAEgAEEuai0AADoAFiABQRdqQTBBCiADIAAtABAbIgNBASADQQFLGxABIAFBFmohBCAAKAIUIQEgAyECA0AgAiAEaiABIAFBCm4iAUF2bGpBMHI6AAAgAkF/aiICDQALIAAgACgCFEEBajYCFCADQRdqC8QFAQl/IwBBEGsiAyQAIAAQACAAIAE2AhQgACACLQAAOgAQIABBEWogAi0AASIIOgAAIABBKGpCADcAACAAQSBqQgA3AAAgAEIANwAYQQAhAUEAIQIDQCADQQlqIAJqIAAgAWotAAA6AAAgAkEBaiICQQNGBEAgACAEaiICQRtqIAMtAAsiBUE/cSIGQZAIai0AADoAACACQRhqIAMtAAkiB0ECdiIJQZAIai0AADoAACACQRpqIAMtAAoiCkECdEE8cSAFQQZ2ciILQZAIai0AADoAACACQRlqIAdBBHRBMHEgCkEEdnIiBUGQCGotAAA6AAAgBEEEaiEEQQAhAgsgAUEBaiIBQRBHDQALIAMgBjoADyADIAs6AA4gAyAFOgANIAMgCToADAJAIAJFDQAgAkECTQRAIANBCWogAmpBAEEDIAJrEAELIAMgAy0ACSIBQQJ2IgU6AAwgAyADLQALIgdBP3E6AA8gAyABQQR0QTBxIAMtAAoiAUEEdnIiBjoADSADIAFBAnRBPHEgB0EGdnI6AA4gAkF/RwRAIAAgBGpBGGogBUGQCGotAAA6AAAgBEEZaiEBIAJBf2ohBCADQQ5qIQUDfyAAIAFqIAZBkAhqLQAAOgAAIAQEfyABQQFqIQEgBEF/aiEEIAUtAAAhBiAFQQFqIQUMAQUgAUFpagsLIQQLIAJBAksNACAAIARqQRhqQT1BAyACaxABCwJAIAgEQCAAQRhqIQFBACECA0ACQCABIAJqIgUtAABBVWoiBkEESw0AQd8AIQQCQAJAIAZBAWsOBAICAgABC0EtIQQLIAUgBDoAAAsgAkEBaiICQRhHDQALIABBL2otAABBPUcNASAAQS5qLQAAQT1HDQEgAEEtOwAuDAELIABBL2otAABBPUcNACAAQS5qLQAAQT1HDQAgAEEvOwAuCyADQRBqJAALC1cBAEGACAtQEAAAAAIAAAAwAAAAIgAAAEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5Ky8=')
  var ready = null

  var mod = {
    buffer: wasm,
    memory: null,
    exports: null,
    realloc: realloc,
    onload: onload
  }

  onload(function () {})

  return mod

  function realloc (size) {
    mod.exports.memory.grow(Math.max(0, Math.ceil(Math.abs(size - mod.memory.length) / 65536)))
    mod.memory = new Uint8Array(mod.exports.memory.buffer)
  }

  function onload (cb) {
    if (mod.exports) return cb()

    if (ready) {
      ready.then(cb.bind(null, null)).catch(cb)
      return
    }

    try {
      if (opts && opts.async) throw new Error('async')
      setup({instance: new WebAssembly.Instance(new WebAssembly.Module(wasm), imp)})
    } catch (err) {
      ready = WebAssembly.instantiate(wasm, imp).then(setup)
    }

    onload(cb)
  }

  function setup (w) {
    mod.exports = w.instance.exports
    mod.memory = mod.exports.memory && mod.exports.memory.buffer && new Uint8Array(mod.exports.memory.buffer)
  }
}

function toUint8Array (s) {
  if (typeof atob === 'function') return new Uint8Array(atob(s).split('').map(charCodeAt))
  return (require('buf' + 'fer').Buffer).from(s, 'base64')
}

function charCodeAt (c) {
  return c.charCodeAt(0)
}
