[project]
version = "0.1.2"
name = "hyperid"
cincludes = []
cobjects = []
pkgconfig = []

lflags = []

cflags = []

[variants]
default = []

[dependencies]
base64-wasm = "*" # in node_modules/

[repos]
